#!/bin/bash
# Karen - Server Configuration Management Tool
# https://github.com/magicoli/karen

KAREN_DIR=$(dirname $(realpath $BASH_SOURCE))

# Get script directory and load helper functions
. $(dirname $(realpath $0))/app/helpers/init

# log 1 "Active config:
# $(get_config | sed "s/^/\t/")"

# end What a wonderful world

# Main command dispatcher
case "${1:-}" in
    help|--help)
        usage
        detailed_help
        ;;
    php)
        exec "$KAREN_BIN/setup-php" "${@:2}"
        ;;
    caddy)
        exec "$KAREN_BIN/generate-caddy-pools" "${@:2}"
        ;;
    apache)
        exec "$KAREN_BIN/setup-apache-optimization.sh" "${@:2}"
        ;;
    --version)
        echo "$PGM $PGM_VERSION"
        echo "https://github.com/magicoli/karen"
        ;;
    "")
        log 0 "Missing command
        
$(usage)"
        end
        ;;
    *)
        end 1 "Unknown command '$1'
        
$(usage)"
        ;;
esac
