#!/bin/bash

PGM_VERSION=1.0.0

set -euo pipefail

PGM=${PGM:-$(basename "$0")}
TMP=/tmp/$PGM.$$
DEBUG=${DEBUG:-}
KAREN_DEBUG=${KAREN_DEBUG:-}

init_helpers=$(dirname $BASH_SOURCE)
init_base=$(dirname $(dirname $init_helpers))
[ ! -e "$init_base/karen" ] && echo "$PGM: This doesn't look like a karen $init_base" && exit 1

# Loading utils (base functions like log, end, yesno...)
. $init_helpers/utils

# Loading system messages
. $init_helpers/messages

# Loading default parameters
. $init_helpers/defaults

# . $init_helpers/gettext || end 1 Could not load gettext

# From now on, legit KAREN_* are available

ENV_PATTERN="^KAREN_"
CONFIG_PATTERN="^KAREN_(ETC)"
ENV_FILE=$KAREN_BASE/.env

if [ -e "$ENV_FILE" ]; then
    log Reading config from $ENV_FILE
    . $ENV_FILE
else
    log Launching installation
    . $KAREN_HELPERS/install
fi

# compgen -v | egrep "$ENV_PATTERN" | grep -E "^[A-Z0-9_]+$" || end $? error_empty_config

# Export Karen environment
exports=$(compgen -v | egrep "$ENV_PATTERN" | grep -E "^[A-Z0-9_]+$") || end $? error_empty_config
[ -n "$exports" ] && export $(compgen -v | egrep "$ENV_PATTERN")

log $BASH_SOURCE processed
