#!/bin/bash

PGM_VERSION=1.0.0

set -e

PGM=${PGM:-$(basename "$0")}
TMP=/tmp/$PGM.$$
DEBUG=${DEBUG:-}
KAREN_DEBUG=${KAREN_DEBUG:-}

ENV_PATTERN="^KAREN_"
CONFIG_PATTERN="^KAREN_(ETC)"

init_helpers=$(dirname $BASH_SOURCE)
init_base=$(dirname $(dirname $init_helpers))
[ ! -e "$init_base/karen" ] && echo "$PGM: This doesn't look like a karen $init_base" && exit 1

# Loading utils (base functions like log, end, yesno...)
. $init_helpers/utils

# Loading default parameters
. $init_helpers/defaults

# From now on, legit KAREN_* are available

ENV_FILE=$KAREN_BASE/.env

if [ -e "$KAREN_BASE/.env" ]; then
    . $KAREN_BASE/.env
else
    . $KAREN_HELPERS/install
fi

# Export Karen environment
exports=$(compgen -v | egrep "$ENV_PATTERN" | grep -E "^[A-Z0-9]+$")
[ -n "$exports" ] && export $(compgen -v | egrep "$ENV_PATTERN")
