#!/bin/bash

# app/helpers/install
# Must be called by helpers when config file is not set.

set -euo pipefail

log starting $BASH_SOURCE 

get_config > $TMP.env

cat $TMP.env | wc -l | grep -q "^0" && end 1 "$(system_message error_config_empty)"

# Show environment if requested
echo "I demand a config file."
echo
echo "Custom settings:"
# Ask for KAREN_ETC location
while read var desc; do
    printf "\t"
    read -u1 -e -p "$var ($desc): " -i "${!var}" $var
    export $var
done << EOF
KAREN_ETC local configuration directory
EOF

echo
get_config | sort -n | tee $TMP.env # | sed "s/^/\t/"

echo
yesno -y "Save these settings to $ENV_FILE?" || end 0 "Configuration aborted"

egrep "$CONFIG_PATTERN" $TMP.env > $ENV_FILE || end $? "$(system_message error_config_save_failed): $ENV_FILE"

# Make sure environment is exported
export $(env | egrep "$ENV_PATTERN" | cut -d "=" -f 1)

[ -z "${1:-}" ] \
&& end 0 "Preferences updated, run $PGM --help for available options" \
|| log 0 "Preferences updated"

log $BASH_SOURCE processed
