#!/bin/bash

# Default to reload, but allow override via environment variable
mode=${mode:-reload}
set -e

sudo a2dismod development
sudo a2dismod status
sudo a2enmod production

sudo systemctl $mode php8.3-fpm.service
echo $_ ${mode}ed

sudo systemctl $mode apache2.service
echo $_ ${mode}ed
echo

sudo systemctl status apache2.service --no-pager
echo
